apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: horseservice
  name: horseservice
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: horseservice
status:
  loadBalancer: { }